version: '3.8'

services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_DB: app
            MONGO_INITDB_ROOT_USERNAME: mongouser
            MONGO_INITDB_ROOT_PASSWORD: mongopassword
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

    backend:
        build:
            context: ./backend
        env_file:
            - ./backend/.env.example
        volumes:
            - ./backend:/usr/src/app
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        depends_on: 
            - mongodb

    frontend:
        build:
            context: ./frontend
        volumes:
            - ./frontend:/usr/src/app
        # command: npm run dev -- --host 0.0.0.0
        ports:
            - 5173:5173
        depends_on: 
            - backend

volumes:
    mongodb: